services:
  - type: web
    name: jaluxi-site
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /api/health
    envVars:
      - key: BACKEND_PORT
        value: "8080"
      - key: ADMIN_PASSWORD
        value: "admin"
      - key: DATABASE_URL
        fromDatabase:
          name: jaluxi-db
          property: connectionString
  - type: pserv
    name: jaluxi-db
    plan: free
    databaseName: jaluxi
    user: jaluxi

