services:
  - type: web
    name: jaluxi-site
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /api/health
    envVars:
      - key: BACKEND_PORT
        value: "8080"
      - key: ADMIN_PASSWORD
        value: "admin"

